server:
  port : 8085

spring:
  application:
    name : CONFIG-SERVER

  cloud:
    sever:
      git:
        uri: https://github.com/yashrana81/microservices-config.git
        clone-on-start-up: true